---
- name: Ensure nginx is installed
  package:
    name: nginx
    state: latest

- name: Ensure nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Add nginx configuration for calibre_webui
  template:
    src: nginx_calibre_webui.conf.j2
    dest: /etc/nginx/conf.d/calibre_webui.conf
  notify: nginx_reload

- name: Clone calibre_webui repository
  git:
    repo: '{{ calibre_webui_repo }}'
    dest: '{{ calibre_container_build_tmpdir }}'
    force: true

- name: Update static file url in app config file
  lineinfile:
    path: '{{ calibre_container_build_tmpdir }}/calibre_webui/calibre_webui.cfg'
    regexp: '^STATIC_URL = '
    line: 'STATIC_URL = "https://{{ calibre_server_name }}{{calibre_static_files_url_path}}/"'

- name: Update FLASK_SECRET in app config file
  lineinfile:
    path: '{{ calibre_container_build_tmpdir }}/calibre_webui/calibre_webui.cfg'
    regexp: '^APP_SECRET_KEY = '
    line: 'APP_SECRET_KEY = "{{ calibre_flask_app_secret_key }}"'

- name: Copy static files to static folder
  copy:
    remote_src: true
    src: '{{ calibre_container_build_tmpdir }}/calibre_webui/static/'
    dest: '{{ calibre_static_files_path }}/'

- name: Build docker container
  docker_image:
    name: calibre_webui
    source: build
    build:
      path: '{{ calibre_container_build_tmpdir }}'
      pull: true
      args:
        CALIBRE_UID: '{{ calibre_user_uid }}'
    force_source: true

- name: Launch calibre_webui container
  docker_container:
    name: calibre_webui
    image: calibre_webui
    memory: '{{ calibre_memory_limit }}'
    restart_policy: unless-stopped
    command: /var/www/calibre_webui/run_app.sh
    ports:
      - '127.0.0.1:{{ calibre_docker_port }}:8000'
    volumes:
      - '{{ calibre_data_dir }}:/data/calibre_library'
    tmpfs:
      - /data/tmp

- name: Clean up temp dir
  file:
    path: '{{ calibre_container_build_tmpdir }}'
    state: absent
