---
- name: Ensure nginx, docker, pip are installed
  package:
    name:
      - nginx
      - docker.io
      - python3-pip
    state: present

- name: Ensure py-docker is installed
  pip:
    name: docker

- name: Ensure nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Add nginx configuration for calibre_webui
  template:
    src: nginx_calibre_webui.conf.j2
    dest: /etc/nginx/conf.d/calibre_webui.conf
  notify: nginx_reload

- name: Create local install dir
  file:
    path: '{{ calibre_local_install_dir }}/repo'
    state: directory

- name: Create local config from template
  template:
    src: calibre_webui.cfg.j2
    dest: '{{ calibre_local_install_dir }}/calibre_webui.cfg'

- name: Clone calibre_webui repository
  git:
    repo: '{{ calibre_webui_repo }}'
    dest: '{{ calibre_local_install_dir }}/repo'
    force: true

- name: Copy static files to static folder
  copy:
    remote_src: true
    src: '{{ calibre_local_install_dir }}/repo/calibre_webui/static/'
    dest: '{{ calibre_static_files_path }}/'

- name: Build docker image
  docker_image:
    name: calibre_webui
    source: build
    build:
      path: '{{ calibre_local_install_dir }}/repo'
      pull: true
      args:
        CALIBRE_UID: '{{ calibre_user_uid }}'
    force_source: true

- name: Launch calibre_webui container
  docker_container:
    name: calibre_webui
    image: calibre_webui
    memory: '{{ calibre_memory_limit }}'
    restart_policy: unless-stopped
    command: /var/www/calibre_webui/run_app.sh
    ports:
      - '127.0.0.1:{{ calibre_docker_port }}:8000'
    volumes:
      - '{{ calibre_data_dir }}:/data/calibre_library'
      - '{{ calibre_local_install_dir }}/calibre_webui.cfg:/etc/calibre_webui/calibre_webui.cfg:ro'
    tmpfs:
      - /data/tmp
